- name: Setup local environment
  hosts: "{{ my_host | default('localhost') }}"
  connection: local
  gather_facts: true

  vars:
    packages:
      - bat
      - dconf
      - gh
      - make
      - neovim
      - ripgrep
      - stow
      - tmux

  tasks:
    - name: Ensure packages are installed
      become: true
      become_user: root
      become_method: ansible.builtin.su
      ansible.builtin.dnf:
        name: "{{ packages }}"
        state: present

    - name: Ensure dotfiles are linked
      changed_when: false
      ansible.builtin.command:
        chdir: files
        cmd: make

    - name: Ensure neovim plugin manager is installed
      ansible.builtin.get_url:
        url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
        dest: "{{ ansible_env.HOME }}/.local/share/nvim/site/autoload/plug.vim"
        owner: "{{ ansible_env.USER }}"
        group: "{{ ansible_env.USER }}"
        mode: "0644"

    - name: Ensure neovim plugins are installed
      changed_when: false
      ansible.builtin.command:
        cmd: "nvim +PlugInstall +qall"
